### ISSUE TITLE
SonarLint hibák átvizsgálása

### ISSUE THREAD

**Issue by Sipor** [BME-MIT-IET/iet-hf-2022-dogevok#3]
Az url.js és test/url.js fájlokban a Sonar által jelzett problémák az alábbiak:

- url.js
    -  _Cognitive Complexity of functions should not be too high_: vagyis túlságosan nagy az egész fájlt felölelő névtelen függvény
![kép](https://user-images.githubusercontent.com/79659381/168673717-f6f91cb3-52a1-472d-a1d5-4752f3b896d8.png)

    - _Unused function parameters should be removed_: nem használt függvényparaméter
![kép](https://user-images.githubusercontent.com/79659381/168674432-8febc3bd-0090-4f9c-8e45-ab8b3f3af701.png)

    - _Identical expressions on both sides_:  két helyen előfordul, ennek értelmét kellene megérteni
![kép](https://user-images.githubusercontent.com/79659381/168675040-72999444-5d04-43f2-ab35-95624f5355df.png)

- test/url.js
    - _Attempts should not be made to update "const" variables_: egy konstans változót próbál felülírni
![kép](https://user-images.githubusercontent.com/79659381/168675809-5bc20591-f114-40d7-82c7-c1b624572be3.png)

Ezekre ha van kommentetek írjátok meg, egyébként én is megírom a javasolt változtatásokat, ahol szükséges.

**Comment by CHMarcell** [comment]
>   * _Unused function parameters should be removed_: nem használt függvényparaméter
>     ![kép](https://user-images.githubusercontent.com/79659381/168674432-8febc3bd-0090-4f9c-8e45-ab8b3f3af701.png)
>   * _Identical expressions on both sides_:  két helyen előfordul, ennek értelmét kellene megérteni
>     ![kép](https://user-images.githubusercontent.com/79659381/168675040-72999444-5d04-43f2-ab35-95624f5355df.png)

Én ezt a kettőt gyorsan kijavítom elsőnek, aztán lehet, hogy a többit is.

**Comment by hellcsaba** [comment]
> * test/url.js
>   
>   * _Attempts should not be made to update "const" variables_: egy konstans változót próbál felülírni
>     ![kép](https://user-images.githubusercontent.com/79659381/168675809-5bc20591-f114-40d7-82c7-c1b624572be3.png)
> 

Ezt javítom.

**Comment by CHMarcell** [comment]
> > * _Unused function parameters should be removed_: nem használt függvényparaméter
> >   ![kép](https://user-images.githubusercontent.com/79659381/168674432-8febc3bd-0090-4f9c-8e45-ab8b3f3af701.png)
> > * _Identical expressions on both sides_:  két helyen előfordul, ennek értelmét kellene megérteni
> >   ![kép](https://user-images.githubusercontent.com/79659381/168675040-72999444-5d04-43f2-ab35-95624f5355df.png)
> 
> Én ezt a kettőt gyorsan kijavítom elsőnek, aztán lehet, hogy a többit is.

A #6 Pull requestben ki is javítottam.

**Comment by Sipor** [comment]
Az első hiba (code smell, cognitive complexity too high) szerintem működésileg helyes,  ilyen nagyobb anonymus functiont szoktak használni, így elég filet behúzni a működéshez minden weboldalnak
