### ISSUE TITLE
Test coverage kell

### ISSUE THREAD

**Issue by CHMarcell** [BME-MIT-IET/iet-hf-2022-dogevok#5]
A kódbázis minőségének biztosításához kellene egy tesztfedettség vizsgálat is, hogy lássuk, mit kell javítani/módosítani.

**Comment by hellcsaba** [comment]
Már megcsináltam, lásd a #4 pull requestben.

**Comment by CHMarcell** [comment]
Oké, a #4 sikeres, lezárom.
