### ISSUE TITLE
Url.isEmptyQuery teszt hiányzik

### ISSUE THREAD

**Issue by CHMarcell** [BME-MIT-IET/iet-hf-2022-dogevok#9]
A tesztek mostmár majdnem mindent lefednek, de az Url.isEmptyQuery-re nincs teszt.

**Comment by CHMarcell** [comment]
Nyitottam is hozzá egy pull requestet gyorsan a #10 -ben, ha valaki tud, az nézzen rá.

**Comment by turaib** [comment]
#10 Rendben van
